In [7]:
import pandas as pd
import numpy as np

# Series Data Structure

In [8]:
s = pd.Series([4,5,6,'a','b','c',np.nan,0])

In [10]:
print(s)

0      4
1      5
2      6
3      a
4      b
5      c
6    NaN
7      0
dtype: object

# DataFrame Data Structure

In [13]:
df = pd.DataFrame(
    {
        'Name' : ['Ram','Shyam','Raju','Rani','Rahul'],
        'Age' : [12,15,13,21,18]
    }
)

In [14]:
df

    Name  Age
0    Ram   12
1  Shyam   15
2   Raju   13
3   Rani   21
4  Rahul   18

In [16]:
df.to_csv('output.csv',index=False)

# Exploring Data in the DataSet

In [18]:
df.head()

    Name  Age
0    Ram   12
1  Shyam   15
2   Raju   13
3   Rani   21
4  Rahul   18